on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - binary:stable
        os:
          - ubuntu-latest
          # - macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: iffy/install-nim@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        version: ${{ matrix.version }}
    - name: Install
      run: nimble install -y
    - name: Run tests in default config
      run: nimble test
    - name: Run tests in production config
      run: nimble test -d:usepostmark -d:openregistration -d:release
    - name: Command-line tests
      run: |
        tests/func1.sh
        
