name: Tests
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 15 * *'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - binary:1.6.18
        os:
          - ubuntu-latest
          # - macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: iffy/install-nim@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        version: ${{ matrix.version }}
    #----------------------------------------
    # multi user mode (default)
    #----------------------------------------
    - name: Install
      run: nimble install -y
    - name: Build bins
      run: nimble multiuserbins
    - name: Run tests
      run: |
        export PATH="${PATH}:$(pwd)/bin"
        nimble test
    - name: Command-line tests
      run: |
        export PATH="${PATH}:$(pwd)/bin"
        tests/func1.sh
    #----------------------------------------
    # single user mode
    #----------------------------------------
    - name: Install (single user mode)
      run: nimble singleuserbins
    - name: Run tests (single user mode)
      run: |
        export PATH="${PATH}:$(pwd)/bin"
        nimble -d:relaysingleusermode test

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: docker build --file docker/singleuser.Dockerfile .
    - run: docker build --file docker/multiuser.Dockerfile .

