name: Tests
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 15 * *'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - binary:2.2.4
        os:
          - ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: iffy/install-nim@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        version: ${{ matrix.version }}
    - name: Install libsodium
      run: |
        sudo apt update -q
        sudo apt install -y libsodium-dev
    - name: Install pkger
      run: nimble install -y https://github.com/iffy/pkger/
    - name: Install deps
      run: pkger fetch
    - name: Run tests
      run: |
        export SHOW_LOGS=1
        tests/all.sh

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: docker build --file docker/Dockerfile .

