name: Tests
on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - binary:stable
        os:
          - ubuntu-latest
          # - macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: iffy/install-nim@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        version: ${{ matrix.version }}
    #----------------------------------------
    # multi user mode (default)
    #----------------------------------------
    - name: Install
      run: nimble install -y
    - name: Run tests
      run: nimble test
    - name: Command-line tests
      run: |
        tests/func1.sh
    #----------------------------------------
    # single user mode
    #----------------------------------------
    - name: Install (single user mode)
      run: nimble -d:relaysingleusermode install -y
    - name: Run tests (single user mode)
      run: nimble -d:relaysingleusermode test
        
